docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v4
  versions:
    - v4
    - v3
nav:
  - Home: index.md
  - v4:
      - Overview: v4/overview.md
      - Installation: v4/installation.md
      - Configuration: v4/configuration.md
  - v3:
      - Overview: v3/overview.md
      - Installation: v3/installation.md
      - Configuration: v3/configuration.md
site_name: dot-errorhandler
site_description: "DotKernel's error logging handler"
repo_url: "https://github.com/dotkernel/dot-errorhandler"
plugins:
  - search
